### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by ringo51a** [ringo51a/kyo_tag#24]
### 概要
issueを作成しましたので、ご確認をよろしくお願いします。

### 実装予定の機能
- [ ] トップページ
- [ ] 会員登録・ログイン機能
- [ ] 投稿の一覧・詳細
- [ ] タグの一覧・詳細
- [ ] 投稿されたスポットの一覧・詳細
- [ ] 投稿作成（位置情報は必須、タグのみも可能とする） 
- [ ] 投稿の編集
- [ ] 投稿の削除
- [ ] 検索する
・タグ一覧、スポット一覧、投稿一覧から探す
・フリーワードで探す（部分一致もできる）
・マップから探す
- [ ] パスワード再設定

**（以下はMVP後に実装）**
・おすすめタグから探す（マイページで表示される）
- [ ] メールアドレス変更
- [ ] マイページ、プロフィール作成・編集機能
- [ ] 投稿へのいいね、いいね解除
- [ ] お気に入り
・マイタグ
・マイスポット（ステータス「行きたい」「行った」など変更できる）
- [ ] 通知
・マイタグを含んだ投稿があった場合通知される（マイページ、SNS）
・新規タグ、新規スポットが追加されたら通知される（マイページ、SNS）
- [ ] 混雑状況の表示（API。投稿の詳細で表示される。）
- [ ] 共有（マイタグやマイスポットをSNSで共有）
- [ ] マイスポットからマイプラン作成
- [ ] お問い合わせページ
- [ ] 利用規約、プライバシーポリシー

### 必要なページ
<img width="848" alt="スクリーンショット 2024-05-30 10 18 51" src="https://github.com/ringo51a/kyo_tag/assets/150096388/15136a85-6c07-4f2b-aeda-00c55a45fa72">

**Comment by tmtkzk0823** [comment]
GitHubProjectsが確認できませんでしたので、こちらご確認いただいてもよろしいですか？
(作成してあるが見れない場合、private設定にしてあることが多いです。)
よろしくお願いします。

**Comment by ringo51a** [comment]
確認いただきありがとうございます。
大変申し訳ございません。
設定には「Visibility　This project is currently public.」とあるのですが、存在がない、ということでしょうか。

**Comment by Tsuchiya2** [comment]
確認できました。
概ね良いかと思います。LGTMです。

---

以下のカードはMVP後で良いかと思います。

- パスワード再設定

**Comment by ringo51a** [comment]
ご確認いただきありがとうございました。
パスワード再設定のカードはMVP後に移動いたします。
