### ISSUE TITLE
6/25 レビュー依頼にむけて

### ISSUE THREAD

**Issue by ringo51a** [ringo51a/kyo_tag#28]
## 各種情報
サービス名：京タグ
サービスURL：https://kyo-tag.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] トップページ
- [x] 会員登録・ログイン機能（SNSログインを除く）
- [x] 投稿の一覧・詳細
- [x] タグの一覧・詳細
- [x] 投稿されたスポットの一覧・詳細
- [x] 投稿作成 
- [x] 投稿の編集
- [x] 投稿の削除 
- [x] 検索する  
・タグ一覧、スポット一覧、投稿一覧から探す
- [x] レスポンシブ対応 

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/630e7e8ee35237051927bd3c6e7286c4.png)](https://gyazo.com/630e7e8ee35237051927bd3c6e7286c4)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
